Imports System.Data
Imports System.Data.SqlClient
Module F_Boton_limpiar
    Dim i As Integer
    Public Sub Boton_Limpiar()
        Try
            Boromir.TLbl_x.Text = "0"
            Boromir.TLbl_0.Text = "0"
            Dim apps As String = Boromir.Tab1.SelectedTab.Text
            Select Case apps
                Case "Tipo Escenarios"
                    Tipo_Escenarios.TxtCodigo_cancha.Text = ""
                    Tipo_Escenarios.TxtNombre_cancha.Text = ""
                Case "Tipo Costo"
                    Tipo_Costo.TxtCodigo_costo.Text = ""
                    Tipo_Costo.CBubic_tipocost.Text = ""
                    Tipo_Costo.TxValor_costo.Text = "0"
                Case "Conceptos"
                    Conceptos.CBAplic_concep.Text = ""
                    Conceptos.TxtCodigo_Concep.Text = ""
                    Conceptos.TxtNombre_Concep.Text = ""
                    Conceptos.CbAccion.Text = ""
                Case "Documentos"
                    Documentos.TxtCodigo_doc.Text = ""
                    Documentos.TxtNombre_doc.Text = ""
                Case "Ciudades"
                    Ciudades.TxtCodigo_ciudad.Text = "0"
                    Ciudades.TxtNombre_ciudad.Text = ""
                Case "Zonas"
                    Zonas.TxtCodigo_Zona.Text = "0"
                    Zonas.Txtciudad_zona.Text = "0"
                    Zonas.TxtNombre_Zona.Text = ""
                Case "Terceros"
                    Terceros.TxtCodigo_terce.Text = "0"
                    Terceros.TxtNombre1_terce.Text = ""
                    Terceros.TxtNombre2_terce.Text = ""
                    Terceros.Txtapellido_terce.Text = ""
                    Terceros.TxtApellido_terce2.Text = ""
                    Terceros.TxtTelefono_terce.Text = "0"
                    Terceros.TxtCelular_terce.Text = "0"
                    Terceros.TxtDireccion_terce.Text = ""
                    Terceros.CBTipodoc.Text = ""
                    Terceros.CBoxCiudad_terce.Text = "0"
                    Terceros.Txtcorreo_terce.Text = "correo@email.com"
                    Terceros.CheBoxCliente_terce.Checked = False
                    Terceros.ChBoxProveedor_terce.Checked = False
                    Terceros.ChBoxEmpleado_terce.Checked = False
                Case "Ubicaciones"
                    Ubicaciones.Txtcodigo.Text = "0"
                    Ubicaciones.TxtNombre_ubica.Text = ""
                    Ubicaciones.TxtDireccion_ubica.Text = ""
                    Ubicaciones.TxtTelefono_ubica.Text = "0"
                    Ubicaciones.TxtCelular_ubica.Text = "0"
                    Ubicaciones.TxtCorreo_Ubica.Text = ""
                    Ubicaciones.TxtCedula_ubica.Text = "0"
                    Ubicaciones.TxtNombre1_ubica.Text = ""
                    Ubicaciones.TxtNombre2_ubica.Text = ""
                    Ubicaciones.TxtApellido1_ubica.Text = ""
                    Ubicaciones.TxtApellido2_ubica.Text = ""
                    Ubicaciones.CBoxCiudad_ubica.Text = "0"
                    Ubicaciones.CBoxZona_ubica.Text = ""
                    Ubicaciones.CheckBox1.Checked = False
                Case "Escenario X ubicacion"
                    EscenarioXubica.TxtCodigo_EXU.Text = ""
                    EscenarioXubica.TxtNombre_EXU.Text = ""
                    EscenarioXubica.CBEstado_EXU.Text = ""
                    EscenarioXubica.CBUbic_EXU.Text = "0"
                    EscenarioXubica.CBTipo_EXU.Text = ""
                Case "Turnos"
                    Turnos.TxtCodigo_turno.Text = ""
                    Turnos.TxtNombre_turno.Text = ""
                    Turnos.TxtHora_inicio.Text = ""
                    Turnos.TxtHora_Final.Text = ""
                Case "Costo Turno"
                    Costo_Turno.CBubic_tabla_costo.Text = "0"
                    Costo_Turno.CBtipoescen_costo_turno.Text = ""
                    Costo_Turno.MTxt_hora.Text = ""
                    Costo_Turno.CBLunes.Text = ""
                    Costo_Turno.CBMartes.Text = ""
                    Costo_Turno.CBMiercoles.Text = ""
                    Costo_Turno.CBJueves.Text = ""
                    Costo_Turno.CBViernes.Text = ""
                    Costo_Turno.CBSabado.Text = ""
                    Costo_Turno.CBDomingo.Text = ""
                    Costo_Turno.CBFestivo.Text = ""
                Case "Nueva Reserva"
                    Nueva_Reserva.TxtReserva_reser.Text = ""
                    Nueva_Reserva.CBoxUbicacion_reser.Text = ""
                    Nueva_Reserva.TxtFecha_reser.Text = ""
                    Nueva_Reserva.MTxtHora_reser.Text = ""
                    Nueva_Reserva.TxtDatos_Cod_escen.Text = ""
                    Nueva_Reserva.TxtDatos_escen.Text = ""
                    Nueva_Reserva.TxtDatos_tipocosto.Text = ""
                    Nueva_Reserva.TxtDatos_Costo.Text = ""
                    Nueva_Reserva.TxtDocumento_terce_reser.Text = "0"
                    Nueva_Reserva.Txt_doc.Text = ""
                    Nueva_Reserva.TxtNombre1_terce.Text = ""
                    Nueva_Reserva.TxtNombre2_terce.Text = ""
                    Nueva_Reserva.TxtApellido_terce_reser.Text = ""
                    Nueva_Reserva.TxtApellido2_terce_reser.Text = ""
                    Nueva_Reserva.CBEstado_reser.Text = ""
                    Nueva_Reserva.Btn_buscar.Visible = False
                    Nueva_Reserva.BtnDisponibles_reser.Visible = True
                    Nueva_Reserva.CBlist_disponibles.Items.Clear()
                Case "Facturas"
                    Facturas.TxtFactura_factu.Text = ""
                    Facturas.CBConcepto_factu.Text = ""
                    Facturas.TxtFecha_factu.Text = Today()
                    Facturas.CBoxUbicacion_factu.Text = ""
                    Facturas.TxtDocumento_terce_factu.Text = "0"
                    Facturas.TxtNombre1_factu.Text = ""
                    Facturas.TxtNombre2_factu.Text = ""
                    Facturas.TxtApellido_terce_factu.Text = ""
                    Facturas.TxtApellido2_terce_factu.Text = ""
                    Variables.bf.Clear()
                    Variables.df.Clear()
                Case "Cotizaciones"
                    Cotizaciones.TxtFactura_factu.Text = ""
                    Cotizaciones.CBConcepto.Text = ""
                    Cotizaciones.TxtFecha_factu.Text = Today()
                    Cotizaciones.CBUbicacion.Text = ""
                    Cotizaciones.TxtDocumento_terce_factu.Text = "0"
                    Cotizaciones.TxtNombre1_factu.Text = ""
                    Cotizaciones.TxtNombre2_factu.Text = ""
                    Cotizaciones.TxtApellido_terce_factu.Text = ""
                    Cotizaciones.TxtApellido2_terce_factu.Text = ""
                    Cotizaciones.txt_observaciones.Text = ""
                    Variables.bf.Clear()
                    Variables.df.Clear()
                Case "Pedidos"
                    Pedidos.TxtFactura_factu.Text = ""
                    Pedidos.CBConcepto.Text = ""
                    Pedidos.TxtFecha_factu.Text = Today()
                    Pedidos.CBUbicacion.Text = ""
                    Pedidos.TxtDocumento_terce_factu.Text = "0"
                    Pedidos.TxtNombre1_factu.Text = ""
                    Pedidos.TxtNombre2_factu.Text = ""
                    Pedidos.TxtApellido_terce_factu.Text = ""
                    Pedidos.TxtApellido2_terce_factu.Text = ""
                    Pedidos.txt_observaciones.Text = ""
                    Variables.bf.Clear()
                    Variables.df.Clear()
                Case "Perfiles"
                    Perfiles.TxtCodigo_perfil.Text = ""
                    Perfiles.CBcrear.Text = "NO"
                    Perfiles.TxtNombre_perfil.Text = ""
                    Perfiles.CBconsultar.Text = "NO"
                    Perfiles.CBactualizar.Text = "NO"
                    Perfiles.CBconfirmar.Text = "NO"
                    Perfiles.CBreversar.Text = "NO"
                    Perfiles.CBanular.Text = "NO"
                    Perfiles.CBimprimir.Text = "NO"
                    Perfiles.CBconsola.Text = "NO"
                    Perfiles.CBEstado.Text = ""
                    Perfiles.documentos_admon.Text = "NO"
                    Perfiles.conceptos_admon.Text = "NO"
                    Perfiles.escenarios_admon.Text = "NO"
                    Perfiles.costos_admon.Text = "NO"
                    Perfiles.cuidades_admon.Text = "NO"
                    Perfiles.zonas_admon.Text = "NO"
                    Perfiles.terceros_admon.Text = "NO"
                    Perfiles.ubicaciones_admon.Text = "NO"
                    Perfiles.escenxubica_admon.Text = "NO"
                    Perfiles.tblcostos_admon.Text = "NO"
                    Perfiles.productos_inven.Text = "NO"
                    Perfiles.movimientos_inven.Text = "NO"
                    Perfiles.saldos_inven.Text = "NO"
                    Perfiles.Ordenes_segur.Text = "NO"
                    Perfiles.Pedidos_factu.Text = "NO"
                    Perfiles.facturas_factu.Text = "NO"
                    Perfiles.cotizaciones_factu.Text = "NO"
                    Perfiles.reservas_factu.Text = "NO"
                    Perfiles.administraivos_report.Text = "NO"
                    Perfiles.inventarios_report.Text = "NO"
                    Perfiles.facturacion_report.Text = "NO"
                    Perfiles.perfiles_segur.Text = "NO"
                    Perfiles.usuarios_segur.Text = "NO"
                    Perfiles.claves_segur.Text = "NO"
                    Perfiles.empresa_segur.Text = "NO"
                    Perfiles.Auditoria_segur.Text = "NO"
                    Perfiles.Licencia_segur.Text = "NO"
                Case "Usuarios"
                   Usuarios.TxtContraseña_perfil.Text = ""
                    Usuarios.CBUbica_Usuarios.Text = "0"
                    Usuarios.CBPerfil_usuario.Text = "0"
                    Usuarios.TxtTercero_usua.Text = "0"
                    Usuarios.CBEstado_Usuarios.Text = ""
                    Usuarios.Txtconfirmacontraseña_perfil.Text = ""
                    Usuarios.Txt_usuario_usua.Text = "0"
                    Usuarios.Txtapellido1_usua.Text = ""
                    Usuarios.TxtApellido2_usua.Text = ""
                    Usuarios.TxtCelular.Text = "0"
                    Usuarios.TxtCorreo_usua.Text = ""
                    Usuarios.TxtNombre1_terce.Text = ""
                    Usuarios.TxtNombre2_terce.Text = ""
                    Usuarios.TxtTelefono_usua.Text = "0"
                    Usuarios.LblPerfildes.Text = ""
                    Usuarios.LblNombredoc_terce.Text = ""
                Case "Productos"
                    Productos.Imagen_produc.Image = Image.FromFile(carpeta_imagenes & "\Foto.jpg")
                    Productos.Txtcodigo_produ.Text = ""
                    Productos.Txtcodigoext_produ.Text = ""
                    Productos.TxtNombre_produ.Text = ""
                    ruta_imagen_guardar = ""
                    Productos.TxtCategoria_produ.Text = ""
                    Productos.TxtMarca_produ.Text = ""
                    Productos.TxtUnidad_produ.Text = ""
                    Productos.TxtFechavence_produ.Text = ""
                    Productos.Txtalto_produ.Text = ""
                    Productos.TxtAncho_produ.Text = ""
                    Productos.TxtLargo_produ.Text = ""
                    Productos.TxtCapacidad_produ.Text = ""
                    Productos.Txtdiametro_produ.Text = ""
                    Productos.TxtPeso_produ.Text = ""
                    Productos.TxtColor_produ.Text = ""
                    Productos.Txtiva_produ.Text = ""
                    Productos.Txtdescuento_produ.Text = ""
                    Productos.Txtcompra_produ.Text = ""
                    Productos.TxtVenta_produ.Text = ""
                    Productos.CBVencimiento_produ.Checked = False
                    Productos.TxtFechavence_produ.Visible = False
                    Productos.Txtobservacion_produ.Text = ""
                    Productos.CB_Combo.Text = "NO"
                    Productos.TxtCantidad.Text = "0"
                    Productos.TxtComponente.Text = "0"
                    Productos.GroupCombo.Visible = False
                    Variables.dt.Clear()
                Case "Movimientos"
                    Mov_inventarios.Txtcodigo_movprodu.Text = ""
                    Mov_inventarios.CBConcepto.Text = ""
                    Mov_inventarios.CBUbicacion.Text = ""
                    Mov_inventarios.TxtFecha_reser.Text = Today
                    Mov_inventarios.LblEstado.Text = "AC"
                    Mov_inventarios.gran_descuento.Text = "0"
                    Mov_inventarios.impuesto.Text = "0"
                    Mov_inventarios.neto.Text = "0"
                    Mov_inventarios.gran_total.Text = "0"
                    Mov_inventarios.TxtDocumento_terce_factu.Text = "0"
                    Mov_inventarios.Codigo1.Text = "0"
                    Mov_inventarios.Precio1.Text = "0"
                    Mov_inventarios.Producto1.Text = "*"
                    Mov_inventarios.Impuesto1.Text = "0"
                    Mov_inventarios.Descuento1.Text = "0"
                    Mov_inventarios.Existencia1.Text = ""
                    Mov_inventarios.Unidad1.Text = "*"
                    Mov_inventarios.Cantidad1.Text = "0"
                    Mov_inventarios.TxtFactuproveedor.Text = ""
                    Mov_inventarios.Descuento_Movi.Text = ""
                    Mov_inventarios.LblConcepto.Text = ""
                    Mov_inventarios.LblUbica.Text = ""
                    Variables.dm.Clear()
                    Variables.dm.Clear()
                Case "Empresa"
                    Empresa.TxtNombre.Text = ""
                    Empresa.Txt_nit.Text = "0"
                    Empresa.TxtDireccion.Text = ""
                    Empresa.TxtTelefono_ubica.Text = "0"
                    Empresa.TxtCelular_ubica.Text = "0"
                    Empresa.TxtManuales.Text = ""
                    Empresa.TxtRutaimgpro.Text = ""
                    Empresa.TxtReportes.Text = ""
                    Empresa.TxtCorreo_Ubica.Text = ""
                    Empresa.TxTclave.Text = ""
                    Empresa.Txtsmpt.Text = ""
                    Empresa.Txtpuerto.Text = "0"
                    Empresa.Txtresolucion.Text = ""
                Case "Licencia"
                    Licencia.a1.Text = ""
                    Licencia.a2.Text = ""
                    Licencia.a3.Text = ""
                    Licencia.a4.Text = ""
                    Licencia.a5.Text = ""
                    Licencia.a6.Text = ""
                    Licencia.i1.Text = ""
                    Licencia.i2.Text = ""
                    Licencia.i3.Text = ""
                    Licencia.i4.Text = ""
                    Licencia.i5.Text = ""
                    Licencia.i6.Text = ""
                    Licencia.f1.Text = ""
                    Licencia.f2.Text = ""
                    Licencia.f3.Text = ""
                    Licencia.f4.Text = ""
                    Licencia.f5.Text = ""
                    Licencia.f6.Text = ""
                    Licencia.r1.Text = ""
                    Licencia.r2.Text = ""
                    Licencia.r3.Text = ""
                    Licencia.r4.Text = ""
                    Licencia.r5.Text = ""
                    Licencia.r6.Text = ""
                    Licencia.s1.Text = ""
                    Licencia.s2.Text = ""
                    Licencia.s3.Text = ""
                    Licencia.s4.Text = ""
                    Licencia.s5.Text = ""
                    Licencia.s6.Text = ""
            End Select
        Catch ex As Exception
            MsgBox("Error: " & ex.Message)
        End Try
    End Sub
End Module
